using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Globalization;
using System.Text;

namespace SurveyApi;

public class Faker
{
    public IEnumerable<FakeQuestionData> GetFakeQuestions()
    {

        yield return new FakeQuestionData
        {
            Text = "Kaç çalışanınız var?",
            Answers = new[]
            {
                "Hiç(tekim)",
                "1 - 3",
                "3 - 5",
                "5 - 10",
                "10 - 20",
                "20 +",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Son 2 ayda maaş artışı yaptınız mı?",
            Answers = new[]
            {
                "Evet",
                "Hayır",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Son 2 aydaki nöbet sıklığından memnun musunuz?",
            Answers = new[]
            {
                "Evet",
                "Hayır",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Son 2 ayda ortalama kaç kişi eczanenize uğruyor?",
            Answers = new[]
            {
                "1-10",
                "10-20",
                "20-30",
                "30-50",
                "50+",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Maaş politikanız nasıl?",
            Answers = new[]
            {
                "Asgariden az",
                "Asgariden az + promosyon",
                "Asgari ücret",
                "Asgari ücret + promosyon",
                "Asgari ücretten fazla ama 2 Asgari ücretten az",
                "Asgari ücretten fazla ama 2 Asgari ücretten az + promosyon",
                "2 Asgari ücretten fazla",
                "2 Asgari ücretten fazla  + promosyon",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Kira ücretiniz nasıl?",
            Answers = new[]
            {
                "3000'den az",
                "3000 - 5000 arası",
                "5000 - 7500 arası",
                "7500 - 10000 arası",
                "10000 - 15000 arası",
                "15000 - 25000 arası",
                "25000 - 50000 arası",
                "50000'den fazla",
            }
        };

        yield return new FakeQuestionData
        {
            Text = "Son 2 ayda kaç farklı ecza deposu ile çalıştınız?",
            Answers = new[]
            {
                "Hiç",
                "1-3",
                "3-5",
                "5-10",
                "10-20",
                "20+",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC faturalama modülünü hangi sıklıkla kullanıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC faturalama modülünde hangi sıklıkla hata alıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
                "Almıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC faturalama modülünü kaç çalışanınız biliyor/kullanıyor?",
            Answers = new[]
            {
                "Hiç",
                "Yarısından azı",
                "Yarısı",
                "Yarısından fazlası",
                "Tamamı",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC stok modülünü hangi sıklıkla kullanıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC stok modülünde hangi sıklıkla hata alıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
                "Almıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC stok modülünü kaç çalışanınız biliyor/kullanıyor?",
            Answers = new[]
            {
                "Hiç",
                "Yarısından azı",
                "Yarısı",
                "Yarısından fazlası",
                "Tamamı",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC mobil uygulamasını hangi sıklıkla kullanıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC mobil uygulamasında hangi sıklıkla hata alıyorsunuz?",
            Answers = new[]
            {
                "Günde birkaç kez",
                "Günde bir",
                "Haftada birkaç kez",
                "Haftada bir",
                "Ayda birkaç kez",
                "Ayda bir",
                "Daha seyrek",
                "Kullanmıyorum",
                "Almıyorum",
            }
        };

        yield return new FakeQuestionData
        {
            Required = false,
            Text = "ABC mobil uygulamasını kaç çalışanınız biliyor/kullanıyor?",
            Answers = new[]
            {
                "Hiç",
                "Yarısından azı",
                "Yarısı",
                "Yarısından fazlası",
                "Tamamı",
            }
        };
    }

    public IEnumerable<FakeUserData> GetFakeUser()
    {
        foreach (var u in users)
        {
            var firstname = u.Split(',')[0];
            var lastname = u.Split(',')[1];

            var firstname_normalized = string.Join("", firstname.Normalize(NormalizationForm.FormD).Where(c => char.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark));
            var lastname_normalized = string.Join("", lastname.Normalize(NormalizationForm.FormD).Where(c => char.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark));
            var separator = firstname.Length % 2 == 0 ? "." : "_";
            var emailprovider = lastname.Length % 2 == 0 ? "@gmail.com" : "@hotmail.com";
            var title = firstname.Length + lastname.Length % 2 == 0 ? "ECZANE " + firstname : firstname + " ECZANESI";
            var identifier = string.Empty;

            var counter = 0;
            foreach (var c in u)
            {
                if (counter++ > 12)
                {
                    break;
                }
                identifier += ((int)c).ToString();
            }
            if (identifier.Length > 12)
            {
                identifier = identifier[..12];
            }

            yield return new FakeUserData
            {
                FirstName = firstname,
                LastName = lastname,
                N_FirstName = firstname_normalized,
                N_LastName = lastname_normalized,
                Id = identifier,
                Email = string.Concat(firstname_normalized.ToLower(), separator, lastname_normalized.ToLower(), emailprovider)
            };
        }
    }

    #region data
    string[] users =
   {
        "FATMA,ŞEN",
"AYŞE,KANDEMİR",
"EMİNE,ÇEVİK",
"HATİCE,ERKURAN",
"ZEYNEP,TÜTEN",
"MERYEM,ÖZTÜRK",
"ŞERİFE,YÜZBAŞIOĞLU",
"SULTAN,VURAL",
"HANİFE,YÜCEL",
"ELİF,SÖNMEZ",
"FADİME,ERTEKİN",
"HAVVA,DEDE",
"CEMİLE,UYANIK",
"ZELİHA,ASLAN",
"ZEHRA,AKBULUT",
"SEVİM,ORHON",
"HACER,UZ",
"HAYRİYE,YAVUZ",
"KADRİYE,ERDEM",
"GÜLSÜM,KULAÇ",
"AYSEL,KAYA",
"HALİME,SELVİ",
"HANIM,AKPINAR",
"ASİYE,ABACIOĞLU",
"HAVA,ÇAY",
"DÖNDÜ,IŞIK",
"LEYLA,ÖZER",
"MELEK,ÖZDEMİR",
"ZEKİYE,ÖZTÜRK",
"KEZİBAN,TAHTACI",
"NACİYE,BÜYÜKCAM",
"HÜLYA,KULAKSIZ",
"NURİYE,AKSEL",
"AYTEN,EROĞLU",
"AYNUR,KARAKUM",
"MAKBULE,DAL",
"SANİYE,ÖCAL",
"TÜRKAN,AYHAN",
"GÜLLÜ,YİĞİT",
"NAZMİYE,YARBİL",
"DUDU,CANACANKATAN",
"SAFİYE,GÜMÜŞAY",
"ÖZLEM,MURT",
"HAMİDE,HALHALLI",
"HURİYE,ULUÖZ",
"FERİDE,ŞEYHANLI",
"RUKİYE,ÇALIŞKANTÜRK",
"YASEMİN,YILMAZ",
"ŞÜKRAN,SARAÇOĞLU",
"REMZİYE,SEZER",
"RAHİME,DOĞAN",
"DİLEK,DEMİR",
"RABİA,KAYAYURT",
"SONGÜL,SÜRÜM",
"SEVGİ,YAVAŞİ",
"SELMA,TURGUT",
"YETER,ŞEN TANRIKULU",
"MÜNEVVER,BARBAROS",
"ESMA,ALDİNÇ",
"FİLİZ,TEKİN",
"NURTEN,GÜLŞAN",
"SEHER,KÜFECİLER",
"MELİHA,ALMACIOĞLU",
"SALİHA,ÇİLDİR",
"HEDİYE,TÜRKDOĞAN",
"NAZİFE,KAYA",
"SAADET,ÖNER",
"PERİHAN,ŞELİMAN",
"MEDİNE,YAMAN",
"GÜLER,ATİK",
"FİKRİYE,YİĞİT",
"ZAHİDE,GİRAY",
"HAFİZE,YALÇINKAYA",
"CENNET,KILIÇ",
"GÜLTEN,ŞENTÜRK",
"SEMRA,KARABAĞ",
"MÜZEYYEN,DEĞİRMENCİ",
"ARİFE,BODUROĞLU",
"ELMAS,YILDIZ",
"GÖNÜL,GÜLER",
"RAZİYE,ERASLAN",
"ŞÜKRİYE,ÜZER",
"BEDRİYE,PİŞİRGEN",
"HATUN,ADANIR",
"YILDIZ,KOÇ",
"NECLA,KORKMAZ",
"SERPİL,YENİDOĞAN",
"NURAY,AYDOĞAN",
"HABİBE,ACARBULUT",
"GÜLAY,ERGE",
"ZÜBEYDE,ERDOĞAN",
"NERİMAN,ÖĞÜT AYDIN",
"ARZU,KUŞKU",
"LÜTFİYE,KUCUR TÜLÜBAŞ",
"MELAHAT,PEKTAŞ",
"NURCAN,KAYACAN",
"NERMİN,GÜLEN",
"ÜMMÜ,DOĞAN",
"SİBEL,AYDIN BADILLIOĞLU",
"GÜLŞEN,GÜLEN AKKÜÇÜK",
"KEZBAN,CANDAN",
"SABRİYE,TEMEL",
"GÜLÜZAR,YENİGÜN",
"NURAN,YILDIRIM",
"MERAL,BEDER",
"ELİFE,AKINCI",
"DÖNE,ÖZDEMİR",
"ESRA,ONUK",
"DERYA,AYDOĞAN",
"ŞENGÜL,YILMAZ",
"ALİYE,AKCAN ATASOY",
"KAMİLE,SARAÇOĞLU ÇEKİÇ",
"NİMET,CÖMERT",
"HASİBE,TOPAL",
"ŞAZİYE,KARAHAN",
"PAKİZE,ŞAHİN",
"ŞEFİKA,ÇETİN",
"GÜLSEREN,YILMAZ İNAL",
"SEBAHAT,AYTAÇ",
"NAZLI,YILDIZ ALTUN",
"KIYMET,KİŞİ",
"SAKİNE,GÜNDÜZ",
"ÇİĞDEM,ÖZKURT PÜRCÜ",
"TÜLAY,AK",
"NAİME,URFALI",
"EMEL,KARAMAN",
"ADİLE,MEMETOĞLU",
"FAHRİYE,KAZBEK",
"AZİZE,KİREÇÇİ",
"AYFER,AKIN",
"NESLİHAN,YADİGAROĞLU",
"SATI,YÜKSEL",
"SEMA,ÖZÇELİK ORAL",
"AYŞEGÜL,BABUŞ",
"PINAR,KAPLAN",
"YÜKSEL,AKÖZ",
"NEBAHAT,KARTAL",
"SEMİHA,BİLGİÇ",
"SIDIKA,ERDEN",
"SAİME,TUĞCUGİL",
"FATİME,KUMRAL",
"ESME,ERBAŞ",
"TUĞBA,ORAL",
"SERAP,KILAÇ",
"CANAN,CENGİZ",
"HÜSNE,YILDIRIM",
"HADİCE,KUTLUCAN BAĞCI",
"BEHİYE,BALABAN",
"ŞADİYE,KAYA",
"GÜLİZAR,BALCI",
"VESİLE,TÜFEKÇİ",
"EBRU,ATAY",
"NEVİN,YARAR",
"GÜLCAN,SEVER",
"NAZİRE,YILDIRIM",
"MEVLÜDE,ARSLAN KAŞDOĞAN",
"SABİHA,ARKAN",
"SEVDA,TUTAŞ",
"NESRİN,ÖZTÜRK",
"SUNA,HAVAS",
"REYHAN,SEÇİR",
"İLKNUR,YILDIZ",
"GÜL,SOYKAMER",
"HÜSNİYE,BEKTAŞ",
"SELİME,BERK",
"DİLBER,GÜL",
"ALİME,GEDİK YILMAZ",
"BİRGÜL,CENGİZ",
"FİDAN,ÇOLAK",
"AZİME,BULUT",
"NEZAHAT,SARI",
"NİHAL,AKYOL",
"SENEM,BAĞCIK",
"BAHRİYE,KUTLUYURDU",
"BAHAR,DEMİRGAN",
"ZÖHRE,YİĞİT KUPLAY",
"NAİLE,GERİLMEZ",
"NECMİYE,DÜZKALIR",
"BİRSEN,KÖKSOY",
"FİRDEVS,GÜLŞEN",
"AYSUN,AKAR",
"ÜMMÜGÜLSÜM,ÖZDOĞAN",
"EŞE,TÖNGE",
"NEJLA,YASA",
"NAFİYE,ÖNVERMEZ",
"MİNE,YILDIRIM",
"NİLGÜN,BİÇER",
"BURCU,KARADEMİR",
"SADİYE,ALIMLI",
"NURGÜL,AKGÜL",
"MEDİHA,HANCIOĞLU",
"HALİSE,BATÇIK",
"GÜLBAHAR,OLPAK",
"MERVE,BOLAT",
"FETHİYE,ARSLAN",
"ÜMMÜHAN,SİĞA",
"SUZAN,MERCAN",
"KUDRET,BOZKURTER",
"LATİFE,GÜLER",
"HİKMET,ERGİNEL",
"NİGAR,ŞAHİN",
"YAŞAR,KADAK",
"AYİŞE,GÜNEY KOCABAŞ",
"VAHİDE,GAYRETLİ AYDIN",
"ŞENAY,HEPKAYA",
"MUKADDES,BAYRAM",
"DURDU,KANIK YÜKSEK",
"NEŞE,KULAK GEDİK",
"CEVRİYE,AKCAN PAKSOY",
"KÜBRA,ESER",
"ASLI,KILIÇ YILDIRIM",
"MUAZZEZ,GİDER",
"FEHİME,KURT",
"MÜNİRE,ELLİALTI",
"ZÜLFİYE,DEMİRTAŞ",
"ŞEHRİ,ARGA",
"SIDDIKA,BAŞKAN VURALKAN",
"AYLA,ALUÇLU",
"GÜLDANE,MUTLU",
"SEVİNÇ,ŞATIR ERTEM",
"FEVZİYE,ENGİZ",
"NADİRE,ÇİPE",
"HAMDİYE,UYSAL",
"İPEK,BAŞER",
"SABAHAT,ARSLAN",
"SELVER,GÖZKAYA",
"NESİBE,ULUTAŞ",
"NURSEL,PİRİM",
"GÜLHAN,ÜSTÜN",
"NURHAN,KIZMAZOĞLU",
"NEFİSE,ULUBA",
"GÜLHANIM,ARSLAN",
"MÜŞERREF,KARAOĞLU",
"SEVİL,ÖZSOY",
"GÜLNAZ,YALÇIN",
"GÜLSEN,SAF",
"DENİZ,VURAL",
"SEDA,DEMİRTAŞ",
"ZARİFE,GENÇPINAR",
"RABİYE,AKASLAN",
"KEVSER,UYĞUN",
"SÜHEYLA,ATAY",
"NEZAKET,ÖNDER SİVİŞ",
"ZÜLEYHA,BAYMAK",
"TUBA,ATAY",
"SEBİHA,GÜVENÇ",
"TESLİME,AKCA ÇAĞLAR",
"DURSUN,ÖZCAN",
"DUYGU,ERDEM ÖZCAN",
"NAHİDE,BAŞMAN",
"MEHTAP,YANNİ",
"SELDA,ÜNAL",
"ŞEMSİ,GÜNDOĞDU",
"BETÜL,ÇELİK",
"İNCİ,USTA GÜÇ",
"ÖZNUR,TANRIVERDİ YILMAZ",
"BEDİA,TAŞKIN",
"GAMZE,ÇETİN",
"SELVİ,YILMAZ ÇİFTDOĞAN",
"NECİBE,GAZETECİ TEKİN",
"NİLÜFER,SARİ",
"ATİYE,KARAKOYUN",
"NUR,KARAKUŞ EPÇAÇAN",
"FİRDES,EKİCİ",
"BEYHAN,AYDINER",
"GÜLSER,AKTAŞ",
"ÇİÇEK,BELGEMEN",
"LEMAN,ÇETİN",
"BİNNAZ,OFLAZ",
"HÜRÜ,BUĞRUL",
"SİNEM,BAYSOY",
"NAZİME,BÜKÜLMEZ",
"KERİME,YILMAZ",
"GÜLİSTAN,BIÇAKÇI",
"MİYASE,KARA",
"MÜRÜVVET,TİMURTAŞ DAYAR",
"SABİRE,ATEŞ",
"YELİZ,BİNBOĞA",
"UMMAHAN,KIZILTEPE",
"ŞEHRİBAN,KAYA",
"NEZİHA,ABSEYİ",
"REFİKA,AMİROVA UÇAN",
"HİLAL,ÖZTÜRK",
"İSMET,TAŞ",
"CEVAHİR,CEYLAN",
"HURİ,KILIÇ",
"FUNDA,EROL",
"ASUMAN,TAYFUN",
"MELİKE,KAYA",
"NURŞEN,KARAKURT",
"FİGEN,BUDUNOĞLU",
"GÜLBEYAZ,ÖZER",
"KİRAZ,SAYGIN",
"GÜLÇİN,ERYAVUZ",
"DÜRDANE,POLAT ÇİÇEK",
"EDA,YILMAZ",
"SEYHAN,ÇELİK",
"GÜLŞAH,ÜNSAL",
"ÜLKÜ,ALPINAR",
"GÜLPERİ,CİNDEMİR",
"ADALET,AKDUMAN",
"SEVAL,UYAR",
"MÜRVET,TÜLPAR",
"İSLİM,AZAK",
"HALİDE,EREN",
"VİLDAN,GÖZCÜ",
"GÜZEL,BAYSAL",
"MELTEM,TUNCEL",
"MÜKERREM,ÇETEMEN",
"ŞÜKRÜYE,YILMAZ",
"NAZAN,GİNİŞ",
"ÖZGE,UZUN",
"YEŞİM,NASIROĞLU",
"DEMET,SEZGİN",
"HAZAL,ÖZTÜRK",
"BEHİCE,YILDIRIM",
"DURDANE,UZUN",
"GÜLİ,BULUR",
"SEVİLAY,DUYSAK",
"GÜNER,YENİN",
"SAMİYE,DEMİREL",
"CAHİDE,SAK",
"YURDAGÜL,KOCABAŞ",
"NURDAN,SARAÇ",
"ŞİRİN,ALKURT KAYIKÇI",
"RESMİYE,YURT",
"VASFİYE,İLKAY",
"GÜNAY,TAVŞAN",
"HAMİYET,ALAY",
"PENBE,ERTEM",
"FATMANA,ÖZEL",
"NURHAYAT,GENÇ",
"SÜREYYA,UĞUZ",
"MESUDE,EVİK",
"MENEKŞE,GENÇ TALAS",
"ALTUN,EKER",
"HÜSNA,ÇİMEN",
"NEVRİYE,ÇIRAKOĞLU",
"DURKADIN,DEMİR GÖÇMEN",
"EMRİYE,ALPAYCI",
"SARİYE,AK",
"SEYRAN,ÇELİK",
"HANDAN,ERCAN",
"NADİYE,ALTUN",
"ESİN,KILIÇ",
"HİDAYET,SARP",
"ÜNZİLE,SÖKER",
"SÜNDÜS,KÖSE",
"BEYAZ,BARÇAK",
"NAZİK,ÖZEKLİ MISIRLIOĞLU",
"GÜLÜMSER,BOLAÇ",
"ÖZGÜL,ASLANALP",
"KADER,ÖRNEK",
"GÜLLÜZAR,AKDOĞAN",
"GÜLÜSTAN,ÖZÇELİK",
"EMİR,ERTÜRKLER",
"KİBAR,SARAL",
"ATİKE,ÖZKAN",
"EDİBE,DEMİRHAN",
"İKBAL,ASLANKARA",
"NEBİYE,EMLAKÇIOĞLU",
"GAZAL,ÖZTÜRK",
"NEDİME,ESER",
"MUKADDER,ÖDEN",
"TENZİLE,DEMİRAY",
"SERVET,AYHAN",
"MUALLA,YAĞCI",
"ZÜHRE,AVCI",
"EMİŞ,BAYGELDİ",
"GÜLESER,BÜKÜM",
"MÜYESSER,DİNCER",
"ŞULE,DOĞAN",
"ZİNNET,EKİZ",
"MÜMİNE,ŞAHİNER",
"MENŞURE,ŞENGÜL",
"OYA,İLGÜN",
"BELGİN,AŞIK",
"AYŞEN,ÖZKAN",
"AYHAN,ŞİRZAİ",
"AYLİN,ÖCALAN",
"MEMNUNE,KABA",
"YADİGAR,TÜLÜCE",
"NEZİHE,AYTEKİN",
"ÜMRAN,KAYA",
"FERİHA,DÜGER",
"NALAN,METİNEREN",
"SEVCAN,BULUT",
"NAGİHAN,ŞAHİN DUYAR",
"MUZAFFER,ÇETİN",
"NADİDE,BÖLÜK",
"SADET,GÖZAÇAN",
"SAİDE,BOZKURT",
"BERRİN,ÖNEY KURNAZ",
"NERGİZ,AY GÜNEY",
"GÜLDEN,KÖYLÜ",
"MÜJGAN,ÖZMEN SÜNER",
"GÜNEŞ,TALAN",
"PERİŞAN,DUMLU",
"AYSER,ZORLU KARAYİĞİT",
"ESMER,KÖYCÜ",
"AYGÜL,UYGUR",
"GÜLSÜN,KABACAOĞLU",
"TÜLİN,TOPALOĞLU",
"GANİME,AYIK",
"LALE,DEMİR",
"MURADİYE,ERDEM",
"SALİHE,KARAMANLI",
"SATİYE,SADİ AYKAN",
"ŞEHRİYE,OKTAY",
"FATIMA,YURTLU",
"PENPE,SALMAN SEVER",
"ZUHAL,CİRİT KOÇER",
"GÜLEY,SORGUN EVCİLİ",
"NAZİLE,NURÇİN",
"REFİYE,BAŞKAN",
"BERNA,KAZANCI",
"SARE,KIYAK YILMAZ",
"PERVİN,METE",
"ÜNZÜLE,UZUN",
"BANU,SAĞDIK",
"KADIN,ARIKAN YORGUN",
"FERDANE,EKİCİ",
"ADLE,KESİM",
"MERCAN,GÜL",
"SEBİLE,YILDIRIM",
"FAZİLET,KARAGÖZ",
"ZÜHAL,PEKEL",
"TELLİ,YAKAR",
"PAMUK,TARLAN",
"GÜLFİDAN,ÇATAK",
"DİDEM,ÇETİNKOR",
"İSMİHAN,SAYIN",
"ŞENNUR,KURT",
"RAİFE,GÜMÜŞ",
"ŞÖHRET,KOCAKAYA ALTUNDAL",
"FADİLE,ÖZMEN",
"CEYLAN,GÜNAY",
"ASYA,DÜZ",
"SAFİNAZ,DİLEK",
"HAKİME,DEMİRTAŞ",
"SOLMAZ,KURTULUŞ",
"HASİNE,KARPUZOĞLU",
"ŞENEL,ERGİNTÜRK ACAR",
"DÜRİYE,BEYOĞLU",
"ZERRİN,SULHAN",
"KAMER,ARSLAN",
"ÜLKER,NUHVEREN",
"MİHRİBAN,AVCIOĞLU",
"GURBET,AHISKALI",
"ZENNURE,ASENA",
"SACİDE,KARACAN ERŞEKERCİ",
"ŞAKİRE,GÖLEMEZ",
"AİŞE,YILDIRIM",
"SATİ,TOHUMOĞLU",
"MECBURE,ÇELİK",
"MUHSİNE,BOZARSLAN",
"NARİN,KÖŞKER",
"BÜŞRA,ÇELİK",
"ALEV,SÜL",
"AKİLE,KORKMAZ",
"NURSEN,TARKAN",
"PEMBE,DUMAN",
"SENİHA,HODJAOGLU",
"BESRA,BALLI",
"GİZEM,ŞATIROĞLU",
"ŞAHİDE,ÖNDE",
"PELİN,LAĞARLI",
"GÖZDE,ÖZÇAY",
"MÜRÜVET,ARSLAN",
"BİRCAN,AKDEMİR",
"ŞEMSE,İÇBAY",
"FADİK,AKIN",
"ZİNET,DEMİRÖZ",
"MENEVŞE,KUYUCU",
"SEDEF,SELÇUK",
"HADİYE,İNCE",
"SATU,ERGÜLÜ EŞMEN",
"SARA,GÖKALP",
"NAFİA,BABACAN",
"FATIM,ÜLGER",
"BİLGE,AYVAZ",
"BESİ,ELVERDİ",
"SEVGÜL,AYDIN",
"TUĞÇE,DEMİREL",
"ŞEVKİYE,CİMBEK",
"DİLŞAH,FIRAT",
"GÜRCÜ,BAHÇEBAŞI",
"HİLMİYE,DAM",
"GÜLLER,KÖROĞLU",
"NAZİKE,ÖZÇELİK",
"NESİME,KARACA",
"ELVAN,SEVEN",
"ASLIHAN,ÖZKURT",
"HESNA,ALTUN",
"İLKAY,BÜYÜKTAŞ",
"ULVİYE,SERTKAYA",
"ŞEYMA,ÖVEN USTAALİOĞLU",
"ÜMMÜGÜL,YALNIZ",
"GÜLÜŞAN,SAVAŞ",
"ESENGÜL,YILMAZ",
"BESİME,YALÇIN",
"HAVANA,BEREKET",
"FADİMANA,KAYA",
"JALE,PEKGÖZ",
"SELVİNAZ,DEMİR",
"BAKİYE,OLMAZ",
"SEÇİL,SEVİNÇ",
"AFİFE,MERHAMETSİZ",
"HACİRE,ÇOBANOĞLU",
"DURİYE,ŞİMŞEK",
"GÜZİDE,BİNNETOĞLU",
"ÖZDEN,ÖĞÜTMEN KOÇ",
"AKGÜL,ÇINKIR",
"CANSU,CAMCI",
"SEVDİYE,YAZAK",
"İFAKAT,NİZAM",
"ARZI,TÜRKOĞLU",
"FAZİLE,DEMİRKOL",
"HİCRAN,AKSAKAL",
"ZÜLBİYE,AKIN",
"DURSUNE,BOZOĞLAN",
"GÜNGÖR,DEĞİRMENCİ",
"SELİN,AYMAN",
"ABİDE,SAÇLI",
"HASRET,KARAKILIÇ",
"İMRAN,BAKANAY ÖZTÜRK",
"EZGİ,PAKÖZ",
"SUPHİYE,ATMIŞ",
"RASİME,AKÇALI",
"ŞERİF,FAKIOĞLU",
"SUNAY,YENİDÜNYA",
"GONCA,ANIK",
"BEDİHA,KÖSEOĞLU",
"GÜLNUR,SONAY",
"ÜLVİYE,ÇELİKER",
"AYŞAN,ÖZDEMİRKIRAN",
"ZİNİ,ÇELİK",
"ZEYTUN,KÖSE",
"BESEY,AKIN",
"SEMAHAT,DURÇ ÖZTÜRK",
"BUKET,İNER KÖKSAL",
"HAYAT,BEREKATOĞLU",
"FETİYE,DİLLİ",
"ZEYCAN,ELBÜKEN",
"GÜLDEREN,BAHÇECİ",
"SALİME,BÜLBÜL",
"ŞEKER,KADI",
"ŞEYDA,IŞIK",
"LUTFİYE,YÜCETÜRK",
"YOSMA,BULUR",
"TEVHİDE,ÖZİŞ",
"KATİBE,ULUBAŞOĞLU",
"MÜLKİYE,AKŞAHİN",
"NEVİM,KARPUZ",
"NEZİRE,YABUL",
"KAFİYE,GÖKSOY",
"MAHMURE,ÜNAL",
"GÜLZADE,IŞIK",
"GÜLCİHAN,KÖKSAL",
"MÜRŞİDE,TEKİŞ",
"GÜLFER,AKSOY",
"SÜNDÜZ,BAŞYURT",
"BİRSEL,YURDSEVEN",
"MÜBERRA,ERDEM",
"EMSAL,MERDEN",
"SAYİME,KISA KARAKAYA",
"NİLAY,SANHAL",
"SULTANİ,ŞAHİN",
"FINDIK,VATANSEVER",
"MELİHAT,BİLGİ",
"UMMUHAN,KAYABAŞ",
"ESEN,GÜRBOSTAN",
"MÜGE,BOLAT",
"MUTEBER,KABİL KUCUR",
"MÜNÜRE,DEĞİRMENCİ AKAR",
"EYLEM,TAYYAR",
"HACERE,ŞAHBAZ",
"HÖRÜ,YANCAR",
"ADEVİYE,OLGAÇ",
"CİHAN,EKİZ",
"MEVLUDE,EREN",
"KANİYE,MALÇOK",
"MUHTEREM,KARASU",
"ERGÜL,KARADAĞ",
"FERDA,TOPRAK",
"NURDANE,SAĞLAM",
"ŞERMİN,ŞAHİN",
"ŞAHİNDE,KEBAPCILAR",
"HANDE,TATAR",
"RAHMİYE,ARSLAN",
"İSMAHAN,YÜCE",
"KERİMAN,TOLA",
"MACİDE,GÜNGÖR",
"ÜLFET,KARAGÖZ",
"FADIMA,ALTINBOĞA",
"IŞIL,YENİÇERİ",
"BELGÜZAR,IŞIKALAN",
"YURDANUR,ÖZDEMİR",
"TEVRAT,GÜRBÜZ",
"ZAİDE,KURU",
"SONA,YURDAM",
"KADİFE,KARA",
"ZERİFE,ÇETİN",
"ŞADUMAN,BAŞARAN",
"NAZİYE,ŞAHİN",
"GÜLLİZAR,ÜREYEN",
"SÜMEYRA,IŞIK",
"SEVİYE,ÖZTÜRK",
"NEFİZE,DOĞAN",
"AYCAN,MESCİ HAFTACI",
"SERMİN,ORHAN",
"ECE,VURAL",
"DÖNÜŞ,EROL",
"SIRMA,BALSAK",
"MÜBECCEL,ÖZDEMİR",
"KAMURAN,ÇİFT",
"MAHİDE,ŞEN",
"SİTTİ,YAZICI EROL",
"SENİYE,BAYRAMOĞLU",
"EMİRE,GENÇDAL",
"MÜMÜNE,DESTEGÜL",
"GÜLEN,ÖZDEMİR",
"FÜSUN,KARÇİN",
"FULYA,ASLAN",
"SEKİNE,BAZ",
"SEMİYE,ALTUNTAŞ",
"DAMLA,ÖZCAN",
"ÜMMÜHANİ,KIRBAŞ",
"ZÜMRÜT,YILMAZ",
"ŞEBNEM,KAYMAN KÖSE",
"BURÇİN,ÇETİN",
"HERDEM,YEŞİLDAĞER",
"FATİ,YÜKSEL",
"GÜLENDAM,KAYAOĞLU",
"ÜMMEHAN,KILIÇ",
"MEYREM,CELTEMEN",
"GÜZİN,GÜNDÜZ",
"İMMİHAN,ŞANLIKAN",
"FAİKA,ÇELİK",
"REŞİDE,ORHAN",
"GÜLŞAN,TANTEKİN",
"FATOŞ,KARAALP",
"HALE,TUNCER",
"DELAL,ATASOY",
"KUMRİ,DOĞAN",
"GÜLLİ,GÖK",
"BELKIS,ÖZDEMİR",
"IRAZ,ÖZKAN",
"ÜMİT,ONAR ŞEKERCİ",
"KUMRU,ASOĞLU",
"ELVEDA,KHALİL",
"İSMİGÜL,YURDAKÖK",
"FİKRET,YILMAZ",
"CELİLE,KESKİN",
"FERİHAN,KOÇARSLAN",
"CEREN,GÖKALP",
"MEHRİ,TUNÇAY",
"ZOZAN,SÜRMEN AKYOL",
"GÖKÇE,AYDIN",
"MAHİ,SEVİNGİL",
"CEYDA,GENÇPINAR",
"GÜLKIZ,AKKAYA",
"ANAKIZ,KUSERLİ",
"FAİZE,BOZKURT",
"SURİYE,ŞİMŞEK",
"YAĞMUR,YILMAZ",
"ENİSE,TALAS",
"İFFET,ÇEVİKER",
"BELMA,KAYNAK",
"MÜFİDE,BAYRAKTAR",
"NASİBE,ÇETİNTAŞ",
"ŞAZİMET,CANTÜRK",
"HANİ,KARADENİZ",
"İNAYET,ALAN",
"BAŞAK,KOYUNCU",
"NURE,KARTAL",
"MAHİNUR,KAYA",
"SEZEN,BAKIRCI",
"MUHTEBER,NAR",
"BESNA,ULUSOY",
"İLHAN,CELİLOĞLU",
"SÜLBİYE,YÜCEL",
"ÖMÜR,DUMAN",
"ANŞA,AKDENİZ",
"MUNİSE,YERAL",
"ŞEHNAZ,GÜRDAL",
"MÜSLÜME,KÜTÜK",
"RAFİYE,KANYILMAZ",
"SERVER,ÖZBEK",
"SÜZAN,UYSAL",
"FEHMİYE,AKIN",
"SÜMEYYE,AKDENİZ",
"PERİZADE,KAPLAN",
"FERHAN,ALBAYRAK",
"ZAHRA,YILDIRIM",
"FİTNET,MÜEZZİNOĞLU",
"PEMPE,AYHAN",
"PERİ,UYGUR",
"ZÜHRA,TÜFENK",
"ASİYA,YÜCEL",
"CAVİDE,DEMİR",
"FATMAGÜL,ÖZDEMİR",
"AYDAN,KIRIŞ",
"İNSAF,KIRASLAN",
"KADİRİYE,SALTÜRK",
"TÜRKİYE,AÇIKGÖZ",
"FELEK,YAĞCI",
"MEHRİBAN,SEVÜK",
"AFET,KAYA",
"İCLAL,DOĞAN",
"KEBİRE,YILDIZ",
"AYŞENUR,BAYTAN",
"ZEMZEM,DEMİRTAŞ",
"MEMDUHA,MUTLU",
"TAYYİBE,GENÇ",
"YÜCEL,AKTUĞ",
"RÜVEYDE,SERİN",
"FADİM,TUNCAY",
"SONAY,GÜNBEY",
"UMAHAN,KAYA",
"BİLGİ,TAŞAR",
"MUHLİSE,AVSEREN",
"GÜLGÜN,BAL",
"ZÜLFİNAZ,BATMAZ",
"MAHİYE,VEZİROĞLU BİRDANE",
"GAZALİ,ARAZ SERVER",
"GÜLSEVİM,GÜLER",
"İKRAM,DALYAN CİLO",
"AKKIZ,KARADAĞ GEÇGEL",
"AYÇA,BAŞTÜRK AYHAN",
"MİHRİYE,ERSOY",
"MÜNİSE,TAY",
"NURCİHAN,ERYILMAZ",
"ÜMMİYE,DEMİR",
"MAHBUP,AYDIN",
"HANİM,OCAK",
"FEYZA,BÖLÜK",
"NİHAN,ÖZMEN",
"OLCAY,ÖZTÜRKERİ",
"ZAKİRE,EKEN",
"SALİYE,AKGÜL",
"NEBİLE,SARICA DAROL",
"AYSEN,CANSEVER",
"HÜMEYRA,AKIN",
"HORİ,GÜZEL",
"LAMİA,ÖZER ÇELİK",
"MÜCELLA,ÇAKIR",
"İREM,AKSUN",
"NEDRET,BALAL",
"FERİŞTAH,BAYAM",
"HÜRMÜZ,ŞAİR",
"YADİKAR,ÜNLÜ",
"MAHİRE,YUMURTAŞ",
"HÜRİYE,AKGÜL",
"NETİCE,AYKAN",
"TAMAM,ALPSAN GÖKMEN",
"SAFURE,CANATAN",
"MUHBET,MUMCUOĞLU",
"ZAHİRE,TAŞKIRAN",
"FERAY,HATİPOĞLU",
"ÖMRİYE,AKYOL",
"HEDLE,SUCAK",
"YAŞARİYE,YILDIZ",
"MELEHAT,AKPINAR",
"BESER,GÖKSEL",
"SEVTAP,KARSLI",
"İMİHAN,ÖZGÜROL",
"SADİFE,ACAR",
"ŞAHSENEM,KALEM",
"GÜLPAŞA,ŞAHİN",
"YAZGÜL,AYDIN",
"HAZİME,DÖKMECİ",
"RUHİYE,GÖRMELİ",
"HÜSNÜYE,ÖZATEŞ",
"HÜRRİYET,SERVET",
"HAZEL,TOPRAK",
"LEYLİ,SÜNER",
"VECİHE,SARIKAYA",
"ADUL,SULUOVA",
"EMETULLAH,SERBEST",
"SEYİDE,EFE",
"NURİ,TOPAK",
"BİNNUR,ATBİNİCİ",
"ZÜMRETE,KIYAK",
"ADVİYE,ÇELİK",
"RUZİYE,ÖZ",
"RİHAN,TEPE",
"MENİCE,ÖZÜAK",
"SEMİRE,ÖNCEL",
"ZİYNET,CANBAZ",
"ÖZCAN,AL",
"FİTNAT,DEMİR",
"ŞEKERNAZ,GÜRER",
"SELBİ,GÜNGÖR",
"SITTIKA,GÜZEL",
"DİLARA,GÖNCÜ",
"MÜSLİME,ÖZDAMAR",
"GÜLFİYE,KARATOPRAK",
"SUAT,ÇAVDAR",
"GÜLSÜME,KARA",
"AYNİ,ÖZ",
"NEVAL,SÖZEN",
"AMŞE,GÖKÇEK",
"MENSURE,KARAKAYA",
"MAKSUDE,GÜNGÖR",
"NAFİZE,ÇEPNİ",
"HAMİYE,KIR",
"KİYMET,ERSOY",
"EMETİ,ÇAĞLAR",
"SEZER,ÖZALP",
"ISMAHAN,EVRENOS",
"İSMİNAZ,BAYRAKTAROĞLU",
"AKKADIN,USLUSOY",
"SAFFET,SARI",
"İMREN,ATALAY",
"AVAŞ,TOPKARA",
"NURA,BEKTAŞ",
"MAŞALLAH,TENEKECİ",
"ZÜLFÜ,ÇAĞIL",
"İSMİ,MERTOL",
"ZÜLFİ,TAŞ",
"SELVET,HIDIROĞLU",
"GÜLCEMAL,ŞEN GÖKÇEİMAM",
"ÜMÜŞ,KARAHAN",
"ZEKİNE,ÖNAL MUSALAR",
"FADEN,DEMİREL",
"MAVİŞ,YACI",
"AMİNE,IŞIKLI",
"BAĞDAT,KILIÇ",
"HANEY,ÜLGEN",
"NİĞMET,KÜÇÜKGÖNCÜ",
"AYŞİ,SU KURT",
"ÇAĞLA,KOÇAR",
"HATEM,BALOĞLU",
"BEŞİRE,DUMAN",
"SERFİNAZ,ASLAN",
"ŞAHİNAZ,SARICANBAZ",
"FERAH,SERT",
"DURAN,ALTUN",
"NAVRUZ,GÖRMELİ",
"GEVRİ,YILMAZ GELEBEK",
"NAİDE,AKYOL",
"PERUZE,ÖZAN SANHAL",
"MUHABBET,AKYILMAZ",
"HALİM,BAKAN",
"NADİME,KARAKAN",
"MÜJDE,GÖRKEM",
"SÜNBÜL,CILIZ BASHEER",
"ÇAKIR,KARACAN",
"HASENE,TEN",
"ŞAHİZER,ATLANOĞLU",
"NEFİYE,ÖZTÜRK",
"SADIKA,TOPALOĞLU",
"FEZİLE,SOYDAN",
"ŞAHA,TÜRKAY",
"NAŞİDE,MENTEŞ",
"NİHAYET,PINARBAŞILI",
"VİCDAN,ONAY",
"ÖZGÜR,CERİT",
"ŞAHSİNE,ÜNAL",
"BELKIZ,ALTUN",
"HAVVANA,YILDIZ",
"FEYZİYE,İMAMOĞLU",
"HALİMİ,ÖZDEMİR AKDUR",
"ZEMİNE,YANMAZ",
"SEHERNAZ,BÜBER",
"NAZİ,AKKAYA",
"GÖZEL,BAKAN",
"BEGÜM,TAŞMALI",
"MEKİYE,BULAKÇI",
"DÜRÜYE,BAYRAM",
"AYŞA,AYDIN",
"RESMİGÜL,GERGER",
"EVRİM,YEŞİLKAYA",
"REFİA,DÖNMEZ",
"YELDA,YILMABAŞAR",
"AYTÜL,DİKİCİ",
"İMHAN,ARİFOĞLU",
"ZÜLAL,FİDAN",
"METHİYE,SAKARYA",
"GÜLE,ÖZEN",
"GÜLSEHER,ONAN",
"KISMET,AKHUN",
"VATHA,KIR",
"KİFAYET,ŞAHİN",
"ZEYNİ,SU DUR",
"BESSİ,YAZICI",
"SARAY,GÜRDEMİR",
"MENCİ,ALTINSOY",
"ELÇİN,KALYONCU UÇAR",
"GÜNNUR,ŞAŞMAZ",
"RAMİZE,GÜLCAN",
"NEBAT,KURT GÜNEY",
"CANDAN,ÖZTÜRK",
"ŞEHRİNAZ,ULUTAŞ",
"TÜLÜN,ALTUNA",
"AYYUŞ,GÜREL",
"MİNİRE,KARAKUŞ",
"IŞIK,KILIÇ",
"GÜLTER,ÖZKIRIŞ",
"GÜLHATUN,KAYA",
"ÇEŞMİNAZ,YILMAZ",
"BAHTİYAR,İNCİ KENAR",
"PEYRUZE,DEMİR",
"İFAKET,AKBAŞ ÖNCEL",
"ÇİLEM,EREN",
"GANİMET,BİCAN",
"KERZİBAN,AYDIN",
"MEHDİYE,ÖZDOĞAN KAVZOĞLU",
"MÜESSER,ATEŞ BUDAK",
"CEYHAN,KÖKSAL",
"BEYZA,SARGIN",
"FELEKNAZ,AKKOYUNLU",
"MESRURE,ŞİMŞEK",
"TAHİRE,ÖZTÜRK",
"FEDİME,KAYHAN",
"ZERNİŞAN,TEZER",
"ESMEHAN,KARACAN ",
"NESLİ,ÇAKIR",
"SEFA,UYSAL",
"BAHİRE,GÜRAKAN",
"GÜLENDER,DOKUMACIOĞLU",
"MUAMMER,KIRHAN",
"GAFURE,ÖZDEMİR",
"AYGÜN,KAYA",
"MEVLÜDİYE,GÜL ÖZMEN",
"ŞAYESTE,ESEN",
"TALİYE,AK YILDIRIM",
"GÖKÇEN,EKER",
"NERGİS,ÖZAVCI AYGÜN",
"HACİCE,ÇEKİÇ",
"MİHDİYE,SAVRAN",
"ŞAHSENE,GÖKALP",
"SUSAN,GÖKMEYDAN",
"GÜRSEL,EMRE",
"SADRİYE,KÜTÜKCÜ",
"ÇİMEN,DİKOĞLU",
"ŞAFAK,AKSOY",
"HELİME,GÖRENEKLİ",
"YAŞARE,KOCA",
"BAĞDAGÜL,KILINÇ",
"RAKİBE,BATGİ AZARKAN",
"FATİMA,TÜRKMEN ALBAYRAK",
"ZARİF,OKULU",
"HAFIZA,KİRİŞCİ",
"MAVUŞ,DEDE",
"NEZİFE,KIZMAZ",
"BERİVAN,ARGON",
"HAFİZA,ALICI",
"TÜRKMEN,ARIKAN",
"SÜRİYE,FINDIK GÜVENDİ",
"YONCA,ÜÇER",
"FATMAANA,ÜNAL",
"SEYYARE,YILMAZ",
"SELEN,ÇETİN",
"SELVA,ERGÖZ",
"SABİYE,FİLİZ",
"NEZİHAT,ALABALIK",
"SAİBE,KIZANOĞLU",
"ÖZEN,YAŞAR",
"ÜMMİHAN,ÇELEN",
"BİLGEN,DEMİRELLİ",
"MÜLKİNAZ,DOĞAN",
"FERUZE,DÖNMEZ",
"ELMAST,AKDEMİR",
"MELDA,DANIŞOĞLU",
"HANSE,GÜRSOY",
"NURAL,ŞENER",
"ŞAHİNDER,ABAT",
"HARBİYE,ERGÜN",
"SELFİNAZ,ÇİÇEKBİLEK",
"NOFA,ÜNÜŞ",
"ZÜBEYDA,OĞUZ",
"SUDİYE,KOL",
"MELİS,TOKER",
"MAHBUBE,SU",
"RAHİLE,POLAT",
"RADİYE,KELEŞ",
"MİYESE,SEYREK",
"ELFİDE,ÖZKAN",
"İLMİYE,ASİL",
"AYŞEHAN,TOKTAŞ",
"ŞEMSİYE,ARDIÇ",
"ALYE,ÖZDEMİR",
"ALTIN,SÖZEN",
"HANİMİ,ÇOBANYILDIZI",
"RANA,MÜFTÜOĞLU",
"SAHURE,YEGEN YILMAZ",
"RAHŞAN,AKSOY",
"DİDAR,AKYOL",
"MAİDE,OFLAZ",
"KADİRE,KARAOĞLANOĞLU",
"NAZLİYE,AYAS",
"ÜLGER,KARAKÖSE",
"GÜLSEVEN,GÜVEN MEŞE",
"SALİSE,YEŞİLOVA",
"KEVİ,EŞKAZAN",
"ZİLFİ,GERDAN",
"ZERİF,MUMCUOĞLU",
"İSMEHAN,VATANSEVER",
"AKİFE,KARKIN",
"ASYE,BİLİCİ",
"SEFİYE,ALBAŞ",
"DURNA,GÜNDÜZ",
"TALİA,TURAN",
"EMBİYE,DEMİR",
"HEVİ,BAYRAKÇI",
"NAKİYE,DÖNMEZ",
"BİLGİN,GÜRSOY",
"SÜMBÜL,ÖZER",
"MEHMET,AŞKIN",
"ALİ,KASAPOĞLU",
"MUSTAFA,SARI",
"AHMET,YALÇIN",
"HÜSEYİN,ÖZTÜRK",
"HASAN,BARIŞAN",
"İBRAHİM,ARDA",
"İSMAİL,BARDAKÇI",
"OSMAN,ULU",
"HALİL,KIVRAK",
"ÖMER,BULUT",
"YUSUF,KILAVUZ",
"SÜLEYMAN,TAN",
"RAMAZAN,CANDAN",
"MURAT,EŞFER",
"ABDULLAH,KARAKULAK",
"MAHMUT,BABAYİĞİT",
"SALİH,BARAN",
"KEMAL,ÖZYÖRÜK",
"RECEP,DENİZ",
"YAŞAR,ÖZDEN",
"EMİN,KARAPIÇAK",
"BEKİR,ÖZDEMİR",
"KADİR,SERT",
"BAYRAM,SAKA",
"ŞÜKRÜ,YILMAZ",
"CEMAL,NASUHBEYOĞLU",
"MUSA,İPLİKÇİ",
"NURİ,ÖZEK",
"ADEM,KAYA",
"MEMET,AYYILDIZ",
"METİN,POLAT",
"DURSUN,ÇELİKTEN",
"ORHAN,SERTOĞLU",
"HACI,SARAYLI",
"ARİF,KILIÇOĞLU",
"ŞABAN,SEZEN",
"FATİH,KOCABIYIK",
"ZEKİ,ATILGAN",
"İSMET,DARAMAN",
"İHSAN,ÇİMEN",
"ABDURRAHMAN,KESKİN",
"SABRİ,ALTAŞ",
"YILMAZ,YAVUZ",
"CELAL,GÖKGÜL",
"KAMİL,KAHRAMAN",
"RIZA,GÜNGÖRMEZ",
"HAKKI,TAŞDELEN",
"SELAHATTİN,EMELİ",
"VELİ,KILIÇ",
"MUZAFFER,SINICI",
"HAKAN,BULUT",
"MEVLÜT,GÖKTAŞ",
"DURMUŞ,BAŞAR",
"CEMİL,KOÇ",
"MUHARREM,ÜNAL",
"NECATİ,TÜRKSOY",
"YAKUP,BAYRAK",
"NURETTİN,SEVİNÇ",
"KAZIM,ÇOKER",
"HALİT,KUMBUL",
"EROL,ÖZATA",
"SADIK,SEYREKOĞLU",
"İSA,BOLATTÜRK",
"EKREM,DİRİCAN",
"SAİT,YILMAZ",
"AZİZ,TÜREMENOĞULLARI",
"AYHAN,AYDEMİR",
"SERKAN,DEMİR",
"KENAN,APAYDIN",
"NİYAZİ,DEMİR",
"CENGİZ,YILMAZ",
"NİHAT,DENİZ",
"GÖKHAN,KOYUNCU",
"SELİM,SAĞCAN",
"YUNUS,EVMEZ",
"BİLAL,AKBULUT",
"AYDIN,KÖKSAL",
"HAYDAR,KARA",
"REMZİ,ÖZCAN",
"MUHAMMET,DEMİREL",
"BÜLENT,TİKİCİ",
"UĞUR,TOMBUL",
"İLYAS,ÇİMEN",
"ŞEVKET,ÇİFTCİ",
"MESUT,KELERCİOĞLU",
"FARUK,BÜYÜKKAL",
"SAMİ,BAL",
"HİKMET,KOÇ",
"HAMDİ,AÇAR",
"TAHİR,KARADAVUT",
"ERKAN,DEMİRTAŞ",
"HAMİT,ÖZEL",
"ŞERİF,DUMLUDAĞ",
"ERCAN,AĞCA",
"SİNAN,AKGÜL",
"TAHSİN,BAYRAM",
"ZİYA,BEKLER",
"ADNAN,CEYLAN",
"İRFAN,KOÇER",
"ERDAL,OKUR",
"ABDULKADİR,GENEZ",
"CUMA,KAYA",
"TURAN,KILINÇ",
"CAFER,GÖRMÜŞ",
"SEDAT,DOĞAN",
"İZZET,ÖZLÜ",
"ENVER,YILDIZ BULUT",
"FEVZİ,PULAT",
"HAMZA,SOBAY",
"MUAMMER,COŞKUNER",
"ŞAHİN,PEYNİRCİ",
"VEYSEL,CAN",
"NEVZAT,KILINÇ",
"TEVFİK,ÇİÇEK",
"SALİM,ORAL",
"İLHAN,İNCEOĞLU",
"ERDOĞAN,KAYA",
"ŞAKİR,SÜMER",
"YASİN,DUYAN",
"YÜKSEL,KARAMEŞE",
"SERDAR,KAPAR",
"EMRE,PAKSOY",
"HARUN,KALIPCI",
"ADİL,DÜZCE",
"FİKRET,ÖZTAŞ",
"ENGİN,YILDIRIM",
"HÜSNÜ,ÇELİK",
"ÜMİT,BİÇER",
"İDRİS,CANDAN",
"DAVUT,GÜLBAHAR",
"BURHAN,TURAN",
"HİLMİ,ŞAHİN",
"FERHAT,DOĞAN",
"DURAN,ŞAHİN",
"HAYRETTİN,DÜZGÜN",
"FAHRİ,ŞENCAN",
"EMRAH,AKTEMUR",
"KASIM,ÖZMEN",
"FAHRETTİN,TOY",
"MUHİTTİN,KARADURAK",
"ERHAN,AKTÜRK",
"RASİM,ÖZKAYNAR",
"ZAFER,GÜNEYSU",
"DOĞAN,AYDIN",
"YAVUZ,FİŞEKCİ",
"YAHYA,ESKİMEZ",
"CEVDET,ŞANLIER",
"ZEKERİYA,SELVAN",
"FEHMİ,YÜREK",
"ÖZGÜR,EREL",
"EYÜP,TÜRKAY",
"REŞİT,UTLU",
"VEDAT,YILMAZ",
"SEYİT,VURAL",
"BAHRİ,YILDIRIM",
"KERİM,ÖRDEK",
"ÇETİN,KULAKSIZ",
"FUAT,COŞKUN",
"ÖZCAN,FİLİZAY",
"TURGUT,HASSAN",
"NECMETTİN,YAMAN",
"LEVENT,GÖÇEN",
"HAYRİ,GÖZÜGÜL",
"ŞERAFETTİN,SÖNMEZER",
"SEFER,TAŞKIRAN",
"SELÇUK,GÜNEBAKAN",
"HALİS,OCAK",
"ONUR,BİRİ",
"NAZMİ,YILMAZ",
"AKİF,KAYA",
"FAİK,GÜVEN",
"HACİ,GÜNEYSU",
"TUNCAY,GÜZELKÜÇÜK",
"LÜTFİ,ATBAŞ",
"SATILMIŞ,SEYHAN",
"BAHATTİN,DOĞAN",
"SEYFETTİN,AKKAŞ",
"NAZIM,DİL",
"NECDET,GÜVEN",
"SUAT,DENİZ",
"FİKRİ,BALTACI",
"MÜSLÜM,ÇİÇEK",
"RESUL,SEVEN",
"KAZİM,TAN",
"CAN,BARAN",
"BARIŞ,POSTALLI",
"ERSİN,BULUT",
"NACİ,ARMAĞAN",
"SEBAHATTİN,SOLUK",
"YALÇIN,BAL",
"HIDIR,KAYA",
"ŞEVKİ,TÜRKAY",
"RAHMİ,CORUT",
"ÖZKAN,ÜNÜVAR",
"ŞEYHMUS,ATAY",
"SERVET,KIRAÇ",
"EŞREF,AKOVA",
"VOLKAN,IŞIK",
"HANİFİ,ÖZEN",
"RİFAT,TOPALKARA",
"CEVAT,BOZPOLAT",
"BURAK,SEVER",
"CİHAN,GEDİKLİ",
"ŞENOL,ŞAHAN",
"MUHSİN,KUŞAKÇI",
"ŞEREF,MANAV",
"NEDİM,KARABULUT",
"SADETTİN,AKBAŞ",
"OKTAY,CANBOLAT",
"NECİP,ŞAHİN",
"CAHİT,KARADAĞ",
"ÜNAL,BABA",
"SELAMİ,EFE",
"SIDDIK,SARI",
"RAŞİT,SERTKAYAOĞLU",
"REFİK,UÇAR",
"MÜMİN,ZEYLİ",
"ABUZER,YILMAZ",
"RIDVAN,YENİLMEZ",
"YÜCEL,KURTULUŞ",
"CEM,ÖRENÇ",
"HAŞİM,AKGÜL",
"MAHİR,ÖZGÜR",
"NİZAMETTİN,ÇİNPOLAT",
"TANER,KUŞ",
"SONER,DURSUN",
"MUHAMMED,YARADILMIŞ",
"MECİT,GELEGEN",
"RAFET,ÖLKER",
"ASIM,KARA",
"HİDAYET,GÜLŞAN",
"ERDEM,KAPLAN",
"TURGAY,ÖZTOPRAK",
"GALİP,ÖZMUK",
"DERVİŞ,KAVUKOĞLU",
"AVNİ,KINDIR",
"ABDULKERİM,KEMİK",
"HALİM,SÖKMEN",
"UFUK,KAYRA",
"SAVAŞ,İPEK",
"NAİL,MERCAN",
"ABBAS,KEVKİR",
"ŞEMSETTİN,HAMDEMİRCİ",
"SABAHATTİN,YILMAZ",
"REŞAT,EROĞLU",
"ABİDİN,KARAKAYA",
"BAKİ,ŞAHİN",
"ARSLAN,ERAT",
"FETHİ,TANİN",
"OĞUZ,YEL",
"ÖNDER,TAŞTEKİN",
"TEMEL,ATİLLA",
"ETHEM,OZAN",
"DENİZ,KARADUMAN",
"İLKER,TAZEOĞLU",
"HÜSAMETTİN,DURMUŞ",
"ZEYNEL,AZRAK",
"KEREM,ERZURUM",
"COŞKUN,KARADEMİR",
"FERİT,MELEKOĞLU",
"ŞEFİK,HALİS",
"GAZİ,CANDANER",
"CEMALETTİN,ALTUNÖZ",
"SERHAT,GAZİ",
"NAZİF,ARSLAN",
"BASRİ,İNSELÖZ",
"ERGÜN,KOCA",
"TALİP,YEŞİLKAYA",
"EMRULLAH,ÜNAL",
"HAYATİ,TAŞ",
"FAZLI,UYSAL",
"ATİLLA,DEVECİ",
"RİZA,ACAR",
"ESAT,SİL",
"CAVİT,ÜNGÜR",
"KADRİ,KÜTÜKOĞLU",
"NECMİ,EROĞLU",
"BİROL,ERDOĞAN",
"SEZAİ,TUNÇ",
"İLHAMİ,GÜMÜRDÜ",
"NADİR,KASKALAN",
"CUMALİ,OLCAR",
"FEYZİ,ÇAKMAK",
"KAYA,ALBAY",
"ALPER,AYDIN",
"ALAATTİN,DOĞAN",
"NUSRET,ALBEN",
"RÜSTEM,AVCI",
"ERTUĞRUL,AK",
"DURDU,ÖZBEK",
"SAİM,TEMURTAŞ",
"VEYSİ,TURAN",
"EYYÜP,ÜÇGÜL",
"LATİF,EKİNCİ",
"TOLGA,ERDOĞMUŞ",
"BEŞİR,ALTAŞ",
"NURULLAH,KAÇIRA",
"HULUSİ,KANKILIÇ",
"SEMİH,OYNAK",
"TARIK,YAKUT",
"CÜNEYT,BERENT",
"ASLAN,SUZAN",
"SITKI,KARDAŞ",
"TAMER,KAYA",
"OKAN,ASLAN",
"BÜNYAMİN,KANKILIÇ",
"FEYZULLAH,YILMAZ",
"HİMMET,ÜZEN",
"SAMET,GÜLLÜ",
"NAİM,SERT",
"İZZETTİN,DEMİRER",
"RIFAT,ÇAKMAK",
"FIRAT,TEL KANKILIÇ",
"ERTAN,AKBUDAK",
"VAHİT,KAPÇAK",
"ÖKKEŞ,KARADENİZ",
"TAYFUN,DEMİR",
"ABDULAZİZ,ÖZSAYIM",
"UMUT,ÇETİN",
"MEMİŞ,DİLMEN",
"ÜZEYİR,BAŞAK",
"ALAETTİN,ISSI",
"CELALETTİN,TURĞUT",
"ABDURRAHİM,ÇELİK",
"ABDULBAKİ,ÇOBAN",
"TURHAN,SUVARİ",
"RAİF,AKAY",
"CELİL,YEŞİL",
"ERDİNÇ,ÇELİK",
"SEZGİN,YILDIZ",
"ŞİRİN,BARAN",
"AYKUT,HOŞER",
"TEKİN,SAYIN",
"NEZİR,TAYFUR",
"ABDÜLKADİR,SABAZ",
"MİTHAT,AVCU",
"NEBİ,SUBARİ",
"MÜRSEL,ÖZDEMİR",
"ABDİ,YAKUT",
"BEKTAŞ,YÜKSELMİŞ",
"TALAT,ESEN",
"İSKENDER,BAKAY",
"LÜTFÜ,ÇİÇEK",
"AKIN,YAVUZ",
"BEDRİ,YILDIRIM",
"SEYDİ,HÜSEYNİ",
"FERDİ,CAN",
"İSHAK,GÜLER",
"MİKAİL,İZGİ",
"HAYRULLAH,YILDIZ",
"VEHBİ,AKTAN",
"SEYFİ,DÜZEL",
"SADULLAH,DEĞİRMENCİ",
"RÜŞTÜ,TOKAR",
"ŞEHMUS,ÇEÇEN",
"SABİT,ÖZTÜRK",
"SAFFET,BURULDAY",
"HALUK,ÇETİNKAYA",
"EYYUP,ZENGİN",
"CANER,KARAKUŞ",
"HABİP,KAYAALP",
"İMAM,KARDAŞ",
"NAZİM,ÇOBAN",
"SEFA,YALÇIN",
"GÜRKAN,SÖZER",
"SALAHATTİN,SAVAŞ",
"ETEM,ÖZER",
"NUH,KURALAY",
"TACETTİN,KILINÇ",
"BATTAL,ARACI",
"SERCAN,ALP",
"RECAİ,ALIM",
"OZAN,YÖRÜK",
"BEHÇET,YAVUZ SEZGİN",
"ERGİN,TAŞ",
"NECAT,SEZGİN",
"KAHRAMAN,LEVENT",
"NEŞET,KARAKAŞ",
"MUHLİS,FİLİZ",
"BİNALİ,DADALI",
"GÜRSEL,AYDEMİR",
"RAHİM,ARIKBOĞA",
"SERDAL,AKYÜREK",
"EDİP,GÜNDÜZ",
"ÖZER,GENCAN",
"EREN,YILDIZ",
"LOKMAN,KITAY",
"DEDE,KORKUT",
"OĞUZHAN,İVACIK",
"ABDULVAHAP,YILMAZ",
"GÜVEN,ÇATUK",
"BEYTULLAH,KARAKOYUNLU",
"GÜNGÖR,CİNBİZ",
"İMDAT,CAMGÖZ",
"SADİ,BAŞDAŞ",
"EMİR,HAKYOL",
"ENDER,KILIÇ",
"ABDULHAMİT,ŞEN",
"RUHİ,VAROL",
"ŞENER,SAĞ",
"NAMIK,ÜRÜN",
"YILDIRIM,COŞKUN",
"BAHADIR,BERBER",
"ALİM,ERDOĞAN",
"NUMAN,AKMEŞE",
"NEJDET,GÖKCE",
"MEMDUH,SEVİNÇ",
"MERT,ŞAHİN",
"VAHAP,HEYBET",
"BURHANETTİN,CEYLAN",
"TUFAN,KURT",
"AZMİ,KARABULUT",
"SELMAN,BABADAĞI",
"TUNCER,ŞİRZAİ",
"AYTEKİN,ERTÜRK",
"PAŞA,KADAK",
"BEDİR,ALTIN",
"MUTLU,PARLAK",
"VAKKAS,CEBECİ",
"MELİH,GÖKÇEK",
"CİHAT,BAYANA",
"RAMADAN,BEKAR",
"ŞİNASİ,DEMİRTAŞ",
"ATİLA,EROĞLU",
"MÜCAHİT,VURGAN",
"CUMHUR,KURTPINAR",
"KEMALETTİN,EROĞLU",
"EBUBEKİR,BAĞCI",
"SUPHİ,YAZICI",
"KORAY,SARIÇİÇEK",
"FERİDUN,TIRAŞ",
"MURTAZA,ÇİTİL",
"İSLAM,OĞUZ",
"EYUP,KARA",
"BEDRETTİN,KOÇYİĞİT",
"YUNİS,KÖKSAL",
"DEMİR,BARATALI",
"KÖKSAL,YORGANCI",
"HURŞİT,DEMİR",
"GÜLTEKİN,ORAK",
"MAKSUT,UZUN",
"ŞEYHO,KÖKSAL",
"SEYFULLAH,SÖNMEZ",
"MÜNİR,YILMAZ",
"FETTAH,KILIÇ",
"NAFİZ,BAYRAK",
"SALMAN,TOKATLIOĞLU",
"HADİ,ŞAHİNER",
"HABİB,YERLİKAYA",
"OLCAY,EMİRLİOĞLU",
"BAHTİYAR,GÖKÇE",
"ABDULMECİT,BİÇER",
"ENES,USUL",
"ÇAĞLAR,TURAÇ",
"ABDİL,GÜVEN",
"ABDURAHMAN,ARIK",
"VAHDETTİN,GÜNDÜZ",
"ZİHNİ,GÜLTEKİN",
"ZÜLKÜF,TUNÇ",
"DİLAVER,ÖZKAN",
"NAİF,ÜNAL",
"FEHİM,KANNECİ",
"SIRRI,TEOMAN",
"SATI,BAKLACI",
"MENDERES,BARAN",
"ALİRIZA,SEVİMLİ",
"ZÜBEYİR,SÖYLER",
"RAMİZ,SARIKAYA",
"TAYYAR,KONURALP",
"GÜNAY,DÖNERTAŞ",
"FAZIL,GÖKÇEN",
"ZÜLFÜ,KARATAŞ",
"İSRAFİL,BAŞARGAN",
"HIZIR,KAHRAMAN",
"KAAN,TOKAT",
"ZEYNAL,AYDIN",
"EVREN,GÜNDÜZ",
"CEBRAİL,BARAN",
"ERAY,DEMİREL",
"DURALİ,ÇAVLI",
"ŞENEL,ATAK",
"ERSAN,BÖCÜ",
"CENK,CÖMERT",
"SEYİTHAN,ÖREN",
"GÖKSEL,YILDIRIM",
"HALEF,ŞENGÜLEROĞLU",
"SELAHADDİN,AKKAYA",
"ALAADDİN,İLHAN",
"ZEKAİ,YAYIKÇI",
"YILDIRAY,KOR",
"METE,ŞİRİN",
"GÜRBÜZ,KURT",
"FESİH,AKDEMİR",
"YENER,YAŞAR",
"AYTAÇ,DURUK",
"ARAP,ŞAHİN",
"NASUH,AVŞAR",
"ŞUAYİP,ÖZASLAN",
"ÖKKAŞ,HÜSEYİNOĞLU",
"VURAL,BOZKURT",
"SELAHİTTİN,KÜÇÜKYILDIZ",
"MİKDAT,MENEKŞE",
"MEHMETALİ,TÜRE",
"SEZER,OFLAZOĞLU",
"FADIL,AZAP",
"ANIL,ZAİM",
"ALTAN,DURAN",
"ENİS,AYDUĞAN",
"NEJAT,KOTTAŞ",
"KAMURAN,BACAK",
"ALİCAN,AVCI",
"HANEFİ,AYCAN",
"ASİM,ÖZCAN",
"SAADETTİN,ŞAHİN",
"ŞAH,1",
"MEDENİ,1",
"ABUBEKİR,TOPÇU",
"SEÇKİN,KARLI",
"TUĞRUL,ÖZDEMİR",
"GARİP,EKEN",
"ÖMÜR,KURT",
"NUREDDİN,GÜRPINAR",
"ZÜHTÜ,CÖMERT",
"NESİM,AK",
"ATA,KAÇER",
"KUDRET,KANDEMİR",
"FERHAN,AYDIN",
"ŞAHABETTİN,ONRAT",
"ALPASLAN,ELÇİÇEK",
"ZÜLFÜKAR,YAKAR",
"BESİM,ADIGÜZEL",
"CEYHUN,ÖNDER",
"HAMDULLAH,TEHLİ",
"SULTAN,OSMANCA",
"LUTFİ,USLUBAŞ",
"ABİT,GÖRÜNMEZ",
"SÜREYYA,DAĞ",
"ABDULHALİM,OLGEN",
"ŞAMİL,ATEŞ",
"RAMİS,ÜZÜM",
"KUTBETTİN,ÖZCANLI",
"ELVAN,ŞEKERLER",
"MEMİK,BAKLACI",
"NUSRETTİN,ÇINKIT",
"İBİŞ,BAŞCI",
"KÜRŞAT,KESGİN",
"MUHTEREM,GÖDE",
"İKRAM,ŞENTÜRK",
"GÜRCAN,BİLGİÇ",
"BORA,ÇETİN",
"ŞAFAK,ŞARLAK",
"ZEKERİYE,KERİMOĞLU",
"BOZAN,SELİM",
"MESTAN,YILDIZOĞLU",
"MUHYETTİN,BULUÇ",
"CİHANGİR,DEDE",
"GÖKMEN,YAVUZ",
"ABDO,KÖROĞLU",
"ZAHİR,KOCUBEYOĞLU",
"ÇAĞRI,KARALAR",
"ABDULLATİF,ERDOĞAN",
"KANİ,ÇOPUR",
"FERUDUN,EYİSOY",
"TANJU,ÜSTÜNDAĞ",
"HASİP,KILAVUZ",
"BEHZAT,YÜCEL",
"ERMAN,ÖKTEM",
"ŞADİ,YAŞAN",
"ZÜLFİKAR,USLU",
"AŞIR,BOZOĞLU",
"ABDULBARİ,GÜLTEKİN",
"ÖZDEMİR,KOCASARAÇ",
"ASKER,DURAN",
"MAŞALLAH,ALĞAN",
"AŞKIN,ERDAL",
"GANİ,KAYKA",
"KANBER,BACAKSIZ",
"FERMAN,ÜNALAN",
"ÖNER,CAN BORAN",
"SERHAN,ZEYBEK",
"GÜNER,KILIÇ",
"KURBAN,TEMİZ",
"ZAKİR,KARAKAŞ",
"VEYİS,OĞUZ",
"TİMUR,AYIK",
"ALİŞAN,ETLEÇ",
"SEYDO,PEHLİVAN",
"NİMET,COŞAR",
"HASBİ,KAHYA",
"MÜMTAZ,ÇETİN",
"HAMİ,ATALAY",
"KUBİLAY,YALÇIN",
"MAZHAR,UFACIK",
"FAYSAL,DURMAZ",
"RAGIP,TURMUŞ",
"ABDULHAKİM,ÇİLESİZ",
"FERZENDE,CANPOLAT",
"ATAKAN,ÖZDEMİR",
"FURKAN,KORUCU",
"ULAŞ,ÇOBAN",
"MÜMÜN,TUNCER",
"EFENDİ,YALÇIN",
"CEZMİ,GÖKTAŞ",
"NURİTTİN,DEMİRDAĞ",
"MÜKREMİN,KAYA",
"ÜNSAL,POLAT",
"İLKAY,GÖZCÜ",
"TAYFUR,ÇELİK",
"REMEZAN,BOZAN",
"SEYHAN,KAYA",
"SADRETTİN,İNANMAZ",
"HABİL,AKSÖZ",
"ÇELEBİ,KURT",
"DURAK,BAŞARAN",
"BEHCET,DEMİRTAŞ",
"ZÜLFİ,TUNÇ",
"MUTTALİP,YAŞİT",
"YİĞİT,ÇELİK",
"VASFİ,ÖZDEMİR",
"MÜSLİM,GÜMÜŞÇÜ",
"EKBER,GÖKKOCA",
"AĞA,DEMİRKAPI",
"DİNÇER,KARACA",
"HAMO,ÇEVİRGEN",
"FERAT,DÜNDAR",
"ERCÜMENT,KARAGÖZ",
"MALİK,ŞAHAN",
"MUHAMMER,ELÇİ",
"ALP,ATİLA",
"ABDÜLKERİM,ALBOĞA",
"MÜJDAT,AKTAŞ",
"ABDULHADİ,ASIG",
"EJDER,AKKAN",
"SIDIK,AYDIN",
"HATİP,ATEŞ",
"BEDİRHAN,ATABAY",
"MUHİDDİN,BALTA",
"FEYYAZ,AYDIN",
"NEŞAT,BÖRTA",
"ALPARSLAN,BOĞAN",
"HAKİM,BAYAR",
"POLAT,DEMİR",
"ERSOY,DAL",
"ÜMMET,ÇÖREKLİ",
"NAHİT,HALICI",
"NASIR,GÖKTEPE",
"MAMO,KOLUŞ",
"KAYHAN,KAYA",
"NÜSRET,İNANÇ",
"ERGÜL,ÖZDEMİR",
"TÜRKER,ORMAN",
"ŞIH,NACAR",
"KAMBER,SADIÇ",
"FETİ,POLAT",
"RUŞEN,ÖZKANLI",
"MAZLUM,ÖZEL",
"MİKTAT,ŞENCAN",
"BİLGİN,ŞAŞMAZ",
"ESER,SALDIRAY",
"ERGUN,ŞAHİN",
"MEVLUT,SULTANOĞLU",
"MEDET,SOMAY",
"ÇAĞDAŞ,POLAT",
"SEZAYİ,ŞİRİN",
"BAHADDİN,URUÇ",
"ALAEDDİN,TOLU",
"ERDİ,SÜVERAN",
"FARİS,SÜMER",
"ABDUL,YILMAZ",
"ALATTİN,YILDIZ",
"RAUF,YILDIZ",
"ATALAY,YETKİNŞEKERCİ",
"MENDUH,BAYRAM",
"TAYLAN,SOYTAŞ",
"TURSUN,BOLSOY",
"MİRZE,BİLİCİ",
"CESİM,AYDOĞAN",
"KURTULUŞ,ARPAT",
"GÜRAY,ALIŞIK",
"RIFKI,AKDEMİR",
"KAMER,ŞAHİN",
"MANSUR,ONAT",
"MEHDİ,KARAARSLAN",
"GÜRHAN,GÖKTEN",
"BİŞAR,EVRAN",
"ÖZAY,ERASLAN",
"ŞEYH,DEVECİ",
"ÜMÜT,ARARAT",
"TEYFİK,AKANSEL",
"RESÜL,ULU",
"ÇAĞATAY,TOY",
"SERTAÇ,YILMAZ",
"MÜNÜR,DEVELİ",
"ABDULCELİL,DEMİRCAN",
"MARUF,BÜYÜKDOĞAN",
"MİTAT,GÜLEÇ",
"NECMEDDİN,ERDEM",
"AYDOĞAN,EMET",
"RİDVAN,İLERİ",
"ULVİ,İLBAY",
"DURSUNALİ,IŞIK",
"MULLA,GÜNEŞ",
"OLGUN,GÜNDOĞDU",
"MİRZA,GÜLENAY SÜMER",
"ZAHİT,NADASTEPE",
"MAHSUM,ÜLKEVAN",
"ABDULGANİ,ŞİMŞEK",
"NAFİ,SEĞMEN",
"FERRUH,ÖZKAN",
"CEYHAN,ÖZDİL",
"ABDULSELAM,MERT",
"İDİRİS,MERSİN",
"TAHA,KIRLANGIÇ",
"FETHULLAH,KENDİRLİ",
"SİNO,KARNAS",
"ZEHNİ,KARCIOĞLU",
"ORUÇ,KARAİSMAİLOĞLU",
"TARKAN,KARAHAN",
"BERAT,KARADENİZ",
"CEMALİ,KAN",
"NUR,İNCE",
"VEZİR,YANIK",
"NİZAM,YAĞCIZEYBEK",
"TUNA,TUNCER",
"KIYASETTİN,TOŞUR",
"MACİT,ŞAHİN",
"ZİYAETTİN,SÖNMEZ",
"GÜNDÜZ,SOYER",
"CABBAR,SEZER",
"GÜROL,SANDAL",
"AŞUR,ÖZDEMİR",
"ALPAY,ORDULU ŞAHİN",
"VEYSAL,OMAY",
"ARDA,KÜTÜK",
"FEDAİ,KOYUNCU",
"ATIF,KORKMAZ",
"TAŞKIN,KIRCALI",
"TELAT,KARAAĞAÇ",
"SELAHETTİN,KABAKUŞ",
"HAZIM,İLGEN",
"UTKU,GÖRDÜK",
"M.,GÖKTAŞ",
"TAYYİP,EVREN",
"HALAF,ERTAŞ",
"HİCABİ,ELDEM",
"İNAN,DOĞAN",
"FELEMEZ,DİRİCAN",
"ENSAR,DEMİRTÜRK",
"BAHAETTİN,DEMİR",
"SAYİT,ÇELEN",
"KAŞİF,ÇAĞLAR",
"DÜNDAR,BAŞAR",
"KÜÇÜK,BAŞ",
"DEVRİŞ,BARÇA",
"CABİR,BALCI",
"ALAİTTİN,AYDOS",
"NABİ,İLBAY",
"TEMUR,BOBUŞOĞLU",
"TEOMAN,KIRLI",
"ABDULGAFUR,AÇAR",
"ZİKRİ,BÖYÜK",
"CANİP,YURTDAŞ",
"ORÇUN,YILDIZ",
"BARBAROS,YEGİN",
"DEVRİM,YAKKAN",
"FETULLAH,ULAŞ",
"ÖZDEN,TUNÇ",
"KADEM,TOPER",
"MÜFİT,TEKİN",
"ERSEN,ŞAHİN",
"GÖKAY,ŞAHİN",
"SİRAÇ,SAYİNER",
"ABDULCEBBAR,SARIGÜL",
"ABDÜLAZİZ,ÖZSAYGILI",
"ABDURREZAK,ÖZDEMİR",
"ZABİT,KOLSUZ",
"BESTAMİ,KIRLI",
"ZİVER,KILINÇ",
"ÖZHAN,KEŞKEK",
"MAHFUZ,KEKLİKÇİOĞLU",
"CEVHER,KAYKI",
"KALENDER,KARAKÖK GÜNGÖR",
"ECEVİT,KACEMER",
"GÖRKEM,İŞGÖREN",
"ŞEMSEDDİN,İNCE",
"HÜDAVERDİ,ILGIN",
"ALİSEYDİ,HİÇDURMAZ",
"KUDDUSİ,GÜVERCİN",
"RAHMAN,ESMERAY",
"ABDULMENAF,ERKAN",
"MUHTAR,EREL",
"MASUM,EMLEK",
"GIYASETTİN,DAYLAK",
"SAFA,ÇOMUT",
"CASİM,ÇELİK",
"SEDRETTİN,BOZKURT",
"NAMİ,BOSTANKOLU",
"CESUR,BAHÇECİ",
"SACİT,BAĞ",
"HÜSMEN,ALPARSLAN",
"AYVAZ,ALADAĞ",
"SERACETTİN,AKDEMİR",
"ALİOSMAN,AKÇAYIR",
"ÖZTÜRK,AKÇAY",
"ABDÜL,ZUBAROĞLU",
"BUĞRA,YILMAZ",
"MEHMED,YILMAZ",
"MELİK,YETER",
"ORKUN,YARDIMCI",
"NECATTİN,ÜNVER",
"AYDEMİR,TÜRKYILMAZ",
"BİRCAN,TUTAR",
"CEYLAN,TEPE",
"ADIGÜZEL,TAŞCI",
"MÜKERREM,ŞAHİN",
"BEYHAN,SUSAM",
"RACİ,SÖZEN",
"NEZİH,SİPAHİ",
"BAKIR,SAVRAN",
"FİLİT,SAVRAN",
"HAN,POTA",
"NAZİR,POLAT",
"ŞAHAP,ÖZTÜRK",
"ERKUT,ÖZDEMİR",
"TALHA,ÖZBEY",
"TUNAY,OKÇU",
"HALDUN,NURLU",
"ŞIHO,KURT",
"APTULLAH,KILINÇ",
"SÜRMELİ,KILIÇ",
"ALİHAN,KAPLAN",
"FADİL,KAPLAN",
"BARAN,KAMACI",
"ŞUAYIP,KAHRAMAN",
"CASIM,İNAN",
"ŞAHİSMAİL,GÜNAYDIN",
"İSAK,EZER",
"NADİ,EŞME",
"NESİP,ERSOY",
"BERK,ELMAAĞAÇ",
"ÇOŞKUN,DADLI",
"FERAMUZ,ÇERİK",
"MUSTAN,COŞKUN",
"ASAF,COŞKUN",
"AGİT,BÜYÜKPASTIRMACI",
"ÇERKEZ,BÜRKÜK",
"TEZCAN,BOLKAN",
"HURŞUT,BAYHAN",
"VAROL,BAHADIR",
"DERYA,BAĞCI",
"SADUN,BAĞ",
"İMRAN,AYKOL",
"ZİYATTİN,AYDIN",
"FAZİL,ASİL",
"SAYİM,ARSLANOĞLU",
"ARMAĞAN,ARSLAN",
"ŞEMSİ,ALAN",
"SULHATTİN,AKKOYUN",
"FAYIK,KİRAZ",
"YONUS,BÜYÜKBULUT",
"BABA,IŞIK",
"SIDKI,CENGİZ",
"EFE,GÜNEŞ",
"CİMŞİT,GÖK",
"NURHAN,ALTAŞ",
"YADİGAR,KÖKSAL",
"BERKAN,TANRİVERDİ",
"ABDULKADIR,YILMAZ",
"TUNÇ,BERTAN",
"GÜZEL,BAK",
"RIZVAN,IŞIK",
"ZARİF,ÖZER",
"TUGAY,DEMİRCAN",
"BEDİ,ÖZAYDIN",
"KASİM,SELVİOĞLU",
"SUNAY,BİLGİÇ",
"ZEKAYİ,KOÇ",
"ABDULMUTTALİP,ARSLAN",
"AHMED,BAZİKİ",
"FAHREDDİN,KÜÇÜKÖZKAN",
"M.EMİN,SÜRÜCÜ",
"ŞİHO,UYKUR",
"PEHLÜL,SUMAN",
"BİRKAN,KAYA",
"SAİD,TACİR",
"ASKERİ,ATEŞ",
"OKAY,TANRIKULU",
"ZEKERİYYA,ÖZGÜNER",
"YÜSÜF,KULA",
"SİYAMİ,ERDOĞAN",
"HAFIZ,GEZİCİ",
"KIVANÇ,ANIK",
"CUMAALİ,NART",
"BATUHAN,BAKLALI",
"HAKKİ,MAĞATUR",
"HALİLİBRAHİM,DİNLER",
"HAYREDDİN,ŞİMŞEK",
"ABDULLA,GENÇER",
"KERAMETTİN,ŞAHİN",
"KÜRŞAD,VARICI",
"REMAZAN,SEZGİN",
"ZÜLKİF,KINIK",
"TEFİK,PAKSOY",
"ABDUSSELAM,KALKAN",
"HULİSİ,ÖZTÜRK",
"EMİRHAN,DAYANGAÇ",
"NESİMİ,KAZAN",
"EGEMEN,KOZANOĞLU",
"SEYFEDDİN,ZİLELİGİL",
"ARAFAT,TAŞCI",
"SAYIM,DEMİR",
"DÜZGÜN,SAĞIR",
"KARABEY,BAŞKAK",
"NADİM,ÇELİK",
"ZEYNELABİDİN,TOPTAŞ",
"SERTAN,AKPINAR",
"HAZİM,KIZILDAĞ",
"KAĞAN,KÖSEOĞLU",
"M,ELİK",
"CENGİZHAN,DEMİR",
"NASRETTİN,ALBAYRAK",
"KARİP,YALÇİN",
"CİNDİ,ÖZTAŞ",
"ALLAHVERDİ,DENİZ",
"EFRAHİM,YILDIZ",
"GAFUR,ŞAHİNER",
"TÜRKAY,ÇETER",
"KİBAR,NACAROĞLU",
"KELEŞ,DENİZ",
"KORHAN,KAVMAZ",
"GİYASETTİN,YILDIRIM",
"OGÜN,ERKAN",
"KORKMAZ,ATEŞ",
"ABDURRAZAK,BOZAN",
"VEFA,BAŞYİĞİT",
"VAHDET,1",
"MİHRALİ,KELEŞ",
"HAKİ,ERDOĞMUŞ",
"NAYİF,ÇAKMAK",
"BAYRAMALİ,BİLAL",
"SALAHADDİN,SUNGAR",
"ÖZGÜN,KILIÇ",
"MÜRTEZA,ELÇİ",
"ŞADAN,KOCAMAN",
"BAHİTTİN,TAŞKIRAN",
"EFRAİM,KUTLAR",
"GÜNEY,ÇİFTCİ",
"YEMLİHA,CANDEMİR",
"KARANİ,AYKUŞ",
"ALKAN,ÇELEBİ",
"REİS,YILMAZ",
"HULKİ,BAŞ",
"ERKİN,YAĞLI",
"ERDEN,SELÇUK",
"ZEKERYA,GEZİCİ",
"SERVER,KURT",
"ÜLKÜ,BADEM",
"DOĞUKAN,BERKAY",
"APDULLAH,ÖZTÜRK",
"ABDULVAHİT,DÜNDAR",
"TOSUN,AKAN",
"ERBİL,SAKALLI",
"CEBBAR,GÜL",
"ÜBEYİT,TEVDİK",
"KARA,BULUT",
"ABDURREZZAK,SARIÇİÇEK",
"BERKAY,DURMAN",
"MÜLAYİM,GÖRMÜŞ",
"SANİ,HAŞİMOĞLU",
"SEYFİTTİN,KILINÇ",
"FARAÇ,POLAT",
"EDNAN,ARSLAN",
"KADİM,KALYENCİ",
"ABDÜLHAMİT,TURANOĞLU",
"GAFFAR,ORHAN",
"FEYAT,YILMAZ",
"CELALEDDİN,KUŞ",
"FAYİK,SERİN",
"NECİM,KESER",
"ORAL,ŞAHİN",
"ELMAS,YÜZER",
"ABDULHALİK,ÖZCANOĞLU",
"ABDÜLMECİT,DERE",
"HAMDİN,YETİZ",
"NASIF,ADISANLI",
"SEMİR,AKEL",
"HATEM,TAŞKIN",
"GÖKSAL,MART",
"TAŞTAN,AYDIN",
"AZİM,AKIN",
"REYHAN,ÖNER",
"HİLAL,UÇAR",
"BAŞAR,KORKMAZOĞLU",
"ŞEKİP,NİMETİGİL",
"ALO,ARSLAN",
"RASIM,ÇINAR",
"AGAH,TATLI",
"TURABİ,ATCI",
"MURTEZA,ÖZER",

    };
    #endregion
}
public class FakeUserData
{
    public string Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string N_FirstName { get; set; }
    public string N_LastName { get; set; }
    public string Email { get; set; }
}
public class FakeQuestionData
{
    public string Text { get; set; }
    public string[] Answers { get; set; }
    public bool Required { get; set; } = true;
}